repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
    - id: black
      name: black
      entry: pipenv run black .
      language: system
      types: [python]
    - id: pytest
      name: pytest
      entry: pipenv run pytest
      language: system
      types: [python]
